export const USER_DOES_NOT_EXIST 		= 'USER_DOES_NOT_EXIST'
export const USER_DOES_ALREADY_EXIST 	= 'USER_DOES_ALREADY_EXIST'
export const EMAIL_IS_INVALID 			= 'EMAIL_IS_INVALID'
export const PASSWORD_IS_INCORRECT 		= 'PASSWORD_IS_INCORRECT'

export const DEVICE_DOES_NOT_EXIST 		= 'DEVICE_DOES_NOT_EXIST'
export const DEVICE_DOES_ALREADY_EXIST 	= 'DEVICE_DOES_ALREADY_EXIST'
export const DEVICE_IS_ALREADY_CLAIMED 	= 'DEVICE_IS_ALREADY_CLAIMED'
export const MAC_IS_INVALID 			= 'MAC_IS_INVALID'
export const PIN_IS_INVALID 			= 'PIN_IS_INVALID'
export const PIN_IS_NOT_SET 			= 'PIN_IS_NOT_SET'
export const PIN_IS_INCORRECT 			= 'PIN_IS_INCORRECT'
export const AUTHKEY_IS_INCORRECT 		= 'AUTHKEY_IS_INCORRECT'

export const FIRMWARE_DOES_NOT_EXIST 	= 'FIRMWARE_DOES_NOT_EXIST'

export const LED_STRIP_DOES_NOT_EXIST 	= 'LED_STRIP_DOES_NOT_EXIST'
export const LED_STRIPS_DO_NOT_EXIST 	= 'LED_STRIPS_DO_NOT_EXIST'

export const NOT_AUTHENTICATED			= 'NOT_AUTHENTICATED' // is not 'logged in'
export const NOT_AUTHORIZED 			= 'NOT_AUTHORIZED' // does not have access to requested resource
