apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  selector:
    matchLabels:
      app: web-app
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: web-app
        tier: frontend
    spec:
      containers:
        - name: web-app
          image: localhost:32000/illumino-web-app:latest
          env:
            - name: FRONTEND_API_HTTP_ENDPOINT
              value: https://api.get-illumi.no/graphql
            - name: FRONTEND_API_WS_ENDPOINT
              value: wss://api.get-illumi.no/graphql
          resources:
            limits:
              cpu: 300m
              memory: 300Mi
          ports:
            - containerPort: 31000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-app
  name: web-app-service
spec:
  ports:
    - name: web
      port: 80
      targetPort: 31000
      protocol: TCP
  selector:
    app: web-app
---

