module.exports = {
	USER_DOES_NOT_EXIST: 'USER_DOES_NOT_EXIST',
	USER_DOES_ALREADY_EXIST: 'USER_DOES_ALREADY_EXIST',
	EMAIL_IS_INVALID: 'EMAIL_IS_INVALID',
	PASSWORD_IS_INCORRECT: 'PASSWORD_IS_INCORRECT',

	DEVICE_DOES_NOT_EXIST: 'DEVICE_DOES_NOT_EXIST',
	DEVICE_DOES_ALREADY_EXIST: 'DEVICE_DOES_ALREADY_EXIST',
	DEVICE_IS_ALREADY_CLAIMED: 'DEVICE_IS_ALREADY_CLAIMED',
	MAC_IS_INVALID: 'MAC_IS_INVALID',
	PIN_IS_INVALID: 'PIN_IS_INVALID',
	PIN_IS_NOT_SET: 'PIN_IS_NOT_SET',
	PIN_IS_INCORRECT: 'PIN_IS_INCORRECT',
	SECRET_IS_INCORRECT: 'SECRET_IS_INCORRECT',
	AUTHKEY_IS_INCORRECT: 'AUTHKEY_IS_INCORRECT',

	NOT_AUTHENTICATED: 'NOT_AUTHENTICATED', // is not 'logged in'
	NOT_AUTHORIZED: 'NOT_AUTHORIZED', // does not have access to requested resource
}
